### ISSUE TITLE
AT-2.1: Signup Feature

### ISSUE THREAD

**Issue by katzmaria** [lolaarroyo0215/-CompileSquad-SOEN341_Project_F24-#211]
## Acceptance Test: Signup and Login Functionality

**Issue Tracking:** This acceptance test is for US.02: Signup Feature (#81).

**User Acceptance FI**

**Signup**:
   - User clicks the Sign Up link to navigate to the signup page.
   - User (student) provides their student ID, password, and other necessary information.
   - User (instructor) provides their full name, username, and password for the signup.
   - User submits the signup form

**Comment by Arman-Emami** [comment]
The accpetance test was updated to ensure that it looks more professional and that it follows the criteria for a good acceptance test. 

- Enhanced validation checks during the signup process to ensure error messages are displayed for missing or invalid input fields (e.g., student ID or password).
- Added clarification to the role-based access control, specifying that students and teachers are redirected to their respective welcome pages after a successful login.

These changes improve the completeness and security aspects of the original acceptance test while aligning with the user story requirements.
